// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Chunk

package main

// ChunkSlice is a slice of type Chunk. Use it where you would use []Chunk.
type ChunkSlice []Chunk

// SelectString projects a slice of string from ChunkSlice, typically called a map in other frameworks. See: http://clipperhouse.github.io/gen/#Select
func (rcv ChunkSlice) SelectString(fn func(Chunk) string) (result []string) {
	for _, v := range rcv {
		result = append(result, fn(v))
	}
	return
}

// DistinctBy returns a new ChunkSlice whose elements are unique, where equality is defined by a passed func. See: http://clipperhouse.github.io/gen/#DistinctBy
func (rcv ChunkSlice) DistinctBy(equal func(Chunk, Chunk) bool) (result ChunkSlice) {
Outer:
	for _, v := range rcv {
		for _, r := range result {
			if equal(v, r) {
				continue Outer
			}
		}
		result = append(result, v)
	}
	return result
}
