// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Chunk

package main

// ChunkSlice is a slice of type Chunk. Use it where you would use []Chunk.
type ChunkSlice []Chunk

// Where returns a new ChunkSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv ChunkSlice) Where(fn func(Chunk) bool) (result ChunkSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}
